---
galaxy_info:
  author: "me"
  license: BSD
  min_ansible_version: 1.2
  platforms:
   - name: EL
     versions:
      - 5
      - 6
   - name: Fedora
     versions:
      - 16
      - 17
      - 18
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
   - name: Debian
     versions:
      - wheezy
  categories:
   - system
dependencies: []

